### PR TITLE
fix: Improved handling of empty directories in get_dirs method

### PR DESCRIPTION
**Pull request by Ever3tt**
## Description
@eduNEXT/dedalo @andrey-canon This PR wants to enhance the way in that the method works with null or empty values.
This is a previous used logic, which allows us to get specific values when they are available or to fall back to a default value in case there is no data, null, or empty data.

### CODE REVIEW

**Comment by bra-i-am** [comment]
Hi @Ever3tt, thank you so much for taking the time to send us improvements.

According to my tests, is reached the main goal of this PR: if the theme from "THEME_OPTIONS" is not found, eox-theming uses first the theme defined in EOX_THEMING_DEFAULT_THEME_NAME ('bragi' in common.py or any other if is overridden), and, if none of these are found, uses the default theme from OpenEdx avoiding the app to get down.

I think is a pretty appropriate change. Let me share this with my team and again thanks a lot

**Review by MaferMazu — APPROVED** [review]
Looks good to me.

**Review by bra-i-am — APPROVED** [review]
LGTM!

**Comment by MaferMazu** [comment]
@Ever3tt, can you sign your commit, please?

**Comment by Ever3tt** [comment]
@MaferMazu @bra-i-am it has just been signed :D

**Comment by bra-i-am** [comment]
hi @Ever3tt, I hope you're doing great!

It looks like you haven't signed your commit yet. Maybe you already know how to do it, but if not... to sign it you have to [generate](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key), [add](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account) and [config](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key) a GPG Key. After that, you have to send the commit again and [this](https://github.com/eduNEXT/eox-theming/pull/51/commits) should have a ["Verified"](https://docs.github.com/assets/cb-17614/mw-1440/images/help/commits/verified-commit.webp):

Thank you so much for your help and let us know if you need something n.n

**Pull request merged**
