### PR TITLE
DS-188-eox-theming support for Nutmeg release

### PR DESCRIPTION
**Pull request by JuanDavidBuitrago**
## Description

This PR adds eox-theming support for Nutmeg release

## Testing instructions

1. Use this strain.yml file to create a nutmeg project

```bash
STRAIN_NAME: nutmeg
STRAIN_TUTOR_VERSION: v14.0.5
DEV_PROJECT_NAME: nutmeg_dev
LOCAL_PROJECT_NAME: nutmeg_local
CMS_HOST: studio.nutmeg.edunext.link
LMS_HOST: lms.nutmeg.edunext.link
PLATFORM_NAME: Distro nutmeg
STRAIN_TUTOR_PLUGINS:
  - REPO: tutor-contrib-edunext-distro
    VERSION: v3.0.0-rc1
    EGG: tutor-contrib-edunext-distro==v3.0.0-rc1
    PACKAGE_NAME: distro
    PROTOCOL: ssh
STRAIN_EXTRA_COMMANDS:
  - APP: 'tutor'
    COMMAND: 'distro enable-themes'
STRAIN_VOLUME_OVERRIDES:
  edxapp:
    - DESTINATION: ../../src/edxapp/edx-platform
      LOCATION: /openedx/edx-platform
    - DESTINATION: ../../src/edxapp/eox-tenant
      LOCATION: /openedx/extra_deps/eox-tenant
    - DESTINATION: ../../src/edxapp/eox-theming
      LOCATION: /openedx/extra_deps/eox-theming
STRAIN_EXPORT_VOLUMES:
  - CONTAINER: lms
    LOCATION: /openedx/edx-platform
    DESTINATION: src/edxapp/edx-platform
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-tenant
    DESTINATION: src/edxapp/eox-tenant
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-theming
    DESTINATION: src/edxapp/eox-theming
DISTRO_EOX_THEMING_DPKG:
  index: git
  name: eox-theming
  private: false
  repo: eox-theming
  domain: github.com
  path: eduNEXT
  protocol: https
  variables:
    development: {}
    production: {}
  version: JDB/nutmeg_release_support
```

2. Run to create project

```bash
stack strain dev configure -k export_vols -k override_vols
stack strain dev init
stack strain dev configure -s export_vols -s override_vols
stack strain dev start
```

3. Use  [ednx-test-themes](https://github.com/eduNEXT/ednx-test-themes) repo to test eox-theming

```bash
cd src/edxapp/edx-platform/themes
git clone git@github.com:eduNEXT/ednx-test-themes.git
```
4. In the file `env/apps/openedx/settings/lms/development.py` you must configure the appropriate path

```bash
COMPREHENSIVE_THEME_DIRS.extend(["/openedx/edx-platform/themes/ednx-test-themes/edx-platform"])
```
5. To test each of the cases, the settings shown must be attached to the settings of the microsite, if you don't have a microsite create in `lms.nutmeg.edunext.link:8000/admin/eox_tenant/microsite/` and adds in subdomain key `lms.nutmeg.edunext.link`

```bash
{
    "EDNX_USE_SIGNAL": true,
    "PLATFORM_NAME": "TEST-THEMING",
    "SITE_NAME": "lms.nutmeg.edunext.link",
    "THEME_OPTIONS": {
        "scripts": {
            "/login": [
                {
                    "content": "alert('This is a test for the inline script');",
                    "type": "inline"
                }
            ]
        },
        "theme": {
            "grandparent": "test-3",
            "name": "test-1",
            "parent": "test-2"
        }
    },
    "course_org_filter": [
        "edX"
    ]
}
```
6. Go to browser `lms.nutmeg.edunext.link:8000` and check the theme, something like https://github.com/eduNEXT/ednx-test-themes/blob/master/captures/1-not-auth.png
7. Go to `/login` and check extra-scripts, something like https://github.com/eduNEXT/ednx-test-themes/blob/master/captures/extra-scripts.png
8. Change microsite settings, theme color have to be diferent. Test steps 6. and 7. again. You find something like https://github.com/eduNEXT/ednx-test-themes/blob/master/captures/2-not-auth.png

```bash
        "theme": {
            "grandparent": "test-1",
            "name": "test-3",
            "parent": "test-2"
        }
```
10. Go to `lms.nutmeg.edunext.link:8000/account/settings` and click on `Reset Your Password`, the file generated inside the lms container, in the path `/tmp/openedx/emails/` 

```bash
tutor dev dc exec lms bash
cd ../../tmp/openedx/emails/
```
 Open the file and ckeck something like https://github.com/eduNEXT/ednx-test-themes/blob/master/captures/1-email.png

## Checklist for Merge

- [ ] Tested in a remote environment
- [x] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Review by MaferMazu — CHANGES_REQUESTED** [review]
In this PR, you update the requirements, [but they are not being used](https://github.com/eduNEXT/eox-theming/blob/JDB/nutmeg_release_support/setup.py#L39). In addition, eox-tenant is a requirement of eox-theming and is not within the requirements in base.in

**Comment by JuanDavidBuitrago** [comment]
> In this PR, you update the requirements, [but they are not being used](https://github.com/eduNEXT/eox-theming/blob/JDB/nutmeg_release_support/setup.py#L39). In addition, eox-tenant is a requirement of eox-theming and is not within the requirements in base.in
> 
> We should add eox-tenant in base.in since it is a core dependency. Ref: [OEP-18: Identify Usage Context](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0018-bp-python-dependencies.html#identify-usage-contexts), and if you add eox-tenant we need to update req again: `make update` And to add that the requirements are installed in the setup, here some reference: [eduNEXT openedx plugin cookiecutter](https://github.com/eduNEXT/cookiecutter-openedx-plugin/blob/master/%7B%7B%20cookiecutter.project_slug%20%7D%7D/setup.py#L91) [OpenedX cookiecutter](https://github.com/openedx/edx-cookiecutters/blob/7ba53624404ba0af42e49bc103dae0c166ede251/python-template/%7B%7Bcookiecutter.placeholder_repo_name%7D%7D/setup.py#L136) [OEP-18: Declare Direct Dependencies](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0018-bp-python-dependencies.html#declare-direct-dependencies)
> 
> Other thing we need to check is the contrains.txt; for example in this PR we have [pylint==2.12.2](https://github.com/eduNEXT/eox-theming/blob/a2bf7bbed0eddf6132fd3793240174f18b84d515/requirements/constraints.txt#L13), and in the platform is [pylint==2.13.5](https://github.com/openedx/edx-platform/blob/open-release/nutmeg.master/requirements/edx/testing.txt#L1050) What the contrains file does is restrict some reqs from being updated. The approach I would recommend here is to first compare the [platform constraints](https://github.com/openedx/edx-platform/blob/open-release/nutmeg.master/requirements/constraints.txt) with the current ones, and leave only the necessary constraints. Then update and check if the reqs of our plugin are far from the platform, I would add them in constrain with the version of the platform.

@MaferMazu Thanks for your review, please could you check the new changes?

**Comment by MaferMazu** [comment]
- ✅ The requirements are now being used, and they look good, although I think you missed [coverage](https://github.com/openedx/edx-platform/blob/open-release/nutmeg.master/requirements/edx/testing.txt#L207).
- ✅ Regarding the backends they are perfect.
- ✅ Regarding the tests that you added in the PR, everything worked perfectly for me
- Maybe it would be good to add that microsite configuration you proposed in the [test-case doc](https://docs.google.com/document/d/18urdJPitAu1lUBvYdQcGXm4WRDbKD2eDf4TTGgrlzZU/edit?usp=sharing) and also add the other variables that need to be added in the microsite to make it work
- Maybe it would be good to drop the circleci tests, and add tox that tests are done with python 3.10 (just like in the github workflow so that it goes with the [support windows](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit?usp=sharing))
- And maybe add a note that Koa was not tested, but this is optional, could be discussed later

**Comment by JuanDavidBuitrago** [comment]
> * white_check_mark The requirements are now being used, and they look good, although I think you missed [coverage](https://github.com/openedx/edx-platform/blob/open-release/nutmeg.master/requirements/edx/testing.txt#L207).
> 
>     * white_check_mark Regarding the backends they are perfect.
> 
>     * white_check_mark Regarding the tests that you added in the PR, everything worked perfectly for me
> 
>     * Maybe it would be good to add that microsite configuration you proposed in the [test-case doc](https://docs.google.com/document/d/18urdJPitAu1lUBvYdQcGXm4WRDbKD2eDf4TTGgrlzZU/edit?usp=sharing) and also add the other variables that need to be added in the microsite to make it work
> 
>     * Maybe it would be good to drop the circleci tests, and add tox that tests are done with python 3.10 (just like in the github workflow so that it goes with the [support windows](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit?usp=sharing))
> 
>     * And maybe add a note that Koa was not tested, but this is optional, could be discussed later

@MaferMazu, I made some changes with the last comment.

**Review by MaferMazu — APPROVED** [review]

**Pull request merged**
